import type { Metadata } from "next";
import "cal-sans";
import "./globals.css";
import PrelineScript from ".././components/cust/PrelineScript";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
{children}

      </body>
      <PrelineScript />
    </html>
  );
}
